"""Parses an Azure DevOps URL into its addressable parts.

A pasted URL is a locator, not a full query specification — the import
workflow still has to validate access and resolve the actual backlog level
via the WIQL/work-item APIs. This module only handles the parsing step.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from urllib.parse import unquote, urlparse


class InvalidAzureDevOpsUrlError(ValueError):
    pass


@dataclass(frozen=True)
class ParsedAzureUrl:
    org: str
    project: str
    team: str | None = None
    work_item_id: int | None = None
    backlog_level: str | None = None


_WORK_ITEM_RE = re.compile(r"/_workitems/edit/(\d+)")


def parse_azure_devops_url(url: str) -> ParsedAzureUrl:
    parsed = urlparse(url.strip())
    if parsed.scheme not in ("http", "https"):
        raise InvalidAzureDevOpsUrlError("URL must start with http(s)://")

    segments = [unquote(s) for s in parsed.path.split("/") if s]
    if not segments:
        raise InvalidAzureDevOpsUrlError("URL has no organization/project path")

    # https://dev.azure.com/{org}/{project}/...
    # https://{org}.visualstudio.com/{project}/...
    if parsed.netloc.startswith("dev.azure.com") or parsed.netloc.endswith(".dev.azure.com"):
        if len(segments) < 2:
            raise InvalidAzureDevOpsUrlError("Expected /{org}/{project}/... path")
        org, project = segments[0], segments[1]
        remainder = segments[2:]
    elif ".visualstudio.com" in parsed.netloc:
        org = parsed.netloc.split(".visualstudio.com")[0]
        if not segments:
            raise InvalidAzureDevOpsUrlError("Expected /{project}/... path")
        project = segments[0]
        remainder = segments[1:]
    else:
        raise InvalidAzureDevOpsUrlError(
            "Unrecognized Azure DevOps host — expected dev.azure.com or *.visualstudio.com"
        )

    # Azure DevOps uses two different URL shapes for backlogs depending on
    # whether the team is already implied by the browsing context:
    #   {team}/_backlogs/{level}                     (team-context URL)
    #   _backlogs/backlog/{team}/{level}              (org/project-root URL,
    #                                                   as generated by "Boards > Backlogs")
    # Both must be handled — getting this wrong silently falls back to
    # importing the entire project instead of the intended team/level.
    team = None
    backlog_level = None
    if remainder and remainder[0] not in ("_workitems", "_backlogs", "_boards", "_queries"):
        team = remainder[0]
        remainder = remainder[1:]

    if remainder and remainder[0] == "_backlogs":
        after = remainder[1:]
        if after and after[0].lower() == "backlog":
            after = after[1:]
            if len(after) >= 2:
                team, backlog_level = after[0], after[1]
            elif len(after) == 1:
                backlog_level = after[0]
        elif after:
            backlog_level = after[0]

    work_item_id = None
    match = _WORK_ITEM_RE.search(parsed.path)
    if match:
        work_item_id = int(match.group(1))

    return ParsedAzureUrl(
        org=org,
        project=project,
        team=team,
        work_item_id=work_item_id,
        backlog_level=backlog_level,
    )
